AllCops:
    TargetRubyVersion: 2.3.0

Style/StringLiterals:
    Enabled: false

Metrics/ParameterLists:
    Enabled: false

Metrics/MethodLength:
    Max: 20

Metrics/LineLength:
    Max: 100

Metrics/BlockLength:
    Enabled: false

Metrics/AbcSize:
    Enabled: false
